Entity/WikiEvent.php
<?php

namespace LinkORB\Bundle\WikiBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="LinkORB\Bundle\WikiBundle\Repository\WikiEventRepository")
 */
class WikiEvent
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=32)
     */
    private $type;

    /**
     * @ORM\Column(type="integer")
     */
    private $created_at;

    /**
     * @ORM\Column(type="string", length=64)
     */
    private $created_by;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $wiki_page_id;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $data;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $wiki_id;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getCreatedAt(): ?int
    {
        return $this->created_at;
    }

    public function setCreatedAt(int $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getCreatedBy(): ?string
    {
        return $this->created_by;
    }

    public function setCreatedBy(string $created_by): self
    {
        $this->created_by = $created_by;

        return $this;
    }

    public function getWikiPageId(): ?int
    {
        return $this->wiki_page_id;
    }

    public function setWikiPageId(?int $wiki_page_id): self
    {
        $this->wiki_page_id = $wiki_page_id;

        return $this;
    }

    public function getData(): ?string
    {
        return $this->data;
    }

    public function setData(?string $data): self
    {
        $this->data = $data;

        return $this;
    }

    public function getWikiId(): ?int
    {
        return $this->wiki_id;
    }

    public function setWikiId(?int $wiki_id): self
    {
        $this->wiki_id = $wiki_id;

        return $this;
    }
}

Controller/WikiEventController.php
<?php

namespace LinkORB\Bundle\WikiBundle\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Security("is_granted('IS_AUTHENTICATED_FULLY')")
 * @Route("/wiki/{wikiName}/events")
 */
class WikiEventController extends AbstractController
{
    /**
     * @Route("/", name="wiki_event_index")
     */
    public function indexAction($wikiName)
    {
        if (!$wiki = $this->get('LinkORB\Bundle\WikiBundle\Repository\WikiRepository')->findOneByName($wikiName)) {
            return $this->redirectToRoute('wiki_index');
        }
        $wikiEvents = $this->get('LinkORB\Bundle\WikiBundle\Repository\WikiEventRepository')->findByWikiId($wiki->getId());

        return $this->render('@Wiki/wiki_event/index.html.twig', [
            'wikiEvents' => $wikiEvents,
            'wiki' => $wiki,
        ]);
    }
}

Resources/views/wiki_event/index.html.twig
{% extends '@Wiki/base.html.twig' %}

{% block title %}Wiki: {{ wiki.name }} :Events {% endblock %}

{% block body %}
    <h1>Wiki: {{ wiki.name }} :Events</h1>

    <div class="buttonbox" >
        <a href="{{ path('wiki_index') }}"   class="btn btn-primary" >
            <i class="fa fa-arrow-left" aria-hidden="true"></i>
            Back
        </a>
    </div>

    <div class="row">
        <div class="col-md-12">
            <fieldset>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Type</th>
                            <th>Created At</th>
                            <th>Created By</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for wikiEvent in wikiEvents %}
                        <tr>
                            <td>{{ wikiEvent.id }}</td>
                            <td>{{ wikiEvent.type }}</td>
                            <td>{{ wikiEvent.createdAt|date() }}</td>
                            <td>{{ wikiEvent.createdBy }}</td>
                        </tr>
                        <tr>
                            <td>&nbsp;</td>
                            <td colspan="3" >{{ wikiEvent.data }}</td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="5">no records found</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </fieldset>
        </div>
    </div>

{% endblock %}